using System.Collections.Generic;
using Gomi.Infraestrutura.Models.Financeiro;

namespace Gomi.Infraestrutura.ValueObjects
{
    public class BancosValueObject
    {
        public static IEnumerable<Banco> Dados => new HashSet<Banco>
        {
            new Banco(1, 0, 0, "Banco Bankpar S.A."),
            new Banco(2, 1, 9, "Banco do Brasil S.A."),
            new Banco(3, 3, 5, "Banco da Amazônia S.A."),
            new Banco(4, 4, 3, "Banco do Nordeste do Brasil S.A."),
            new Banco(5, 12, 4, "Banco Standard de Investimentos S.A."),
            new Banco(6, 14, 0, "Natixis Brasil S.A. Banco Múltiplo"),
            new Banco(7, 19, 1, "Banco Azteca do Brasil S.A."),
            new Banco(8, 21, 3, "BANESTES S.A. Banco do Estado do Espírito Santo"),
            new Banco(9, 24, 8, "Banco de Pernambuco S.A. - BANDEPE"),
            new Banco(10, 25, 6, "Banco Alfa S.A."),
            new Banco(11, 27, 2, "Banco do Estado de Santa Catarina S.A."),
            new Banco(12, 29, 9, "Banco Banerj S.A."),
            new Banco(13, 31, 0, "Banco Beg S.A"),
            new Banco(14, 33, 7, "Banco Santander (Brasil) S.A."),
            new Banco(15, 36, 1, "Banco Bradesco BBI S.A."),
            new Banco(16, 37, 0, "Banco do Estado do Pará S.A."),
            new Banco(17, 38, 8, "Banco Banestado S.A."),
            new Banco(18, 39, 6, "Banco do Estado do Piauí S.A. - BEP"),
            new Banco(19, 40, 0, "Banco Cargill S.A."),
            new Banco(20, 41, 8, "Banco do Estado do Rio Grande do Sul S.A."),
            new Banco(21, 44, 2, "Banco BVA S.A."),
            new Banco(22, 45, 0, "Banco Opportunity S.A."),
            new Banco(23, 47, 7, "Banco do Estado de Sergipe S.A."),
            new Banco(24, 62, 0, "Hipercard Banco Múltiplo S.A."),
            new Banco(25, 63, 9, "Banco Ibi S.A. Banco Múltiplo"),
            new Banco(26, 64, 7, "Goldman Sachs do Brasil Banco Múltiplo S.A."),
            new Banco(27, 65, 5, "Banco Lemon S.A."),
            new Banco(28, 66, 3, "Banco Morgan Stanley S.A."),
            new Banco(29, 69, 8, "BPN Brasil Banco Múltiplo S.A."),
            new Banco(30, 70, 1, "BRB - Banco de Brasília S.A."),
            new Banco(31, 72, 8, "Banco Rural Mais S.A."),
            new Banco(32, 73, 6, "BB Banco Popular do Brasil S.A."),
            new Banco(33, 74, 4, "Banco J. Safra S.A."),
            new Banco(34, 75, 2, "Banco CR2 S.A."),
            new Banco(35, 76, 0, "Banco KDB S.A."),
            new Banco(36, 77, 9, "Banco Intermedium S.A."),
            new Banco(37, 78, 7, "BES Investimento do Brasil S.A.-Banco de Investimento"),
            new Banco(38, 79, 5, "JBS Banco S.A."),
            new Banco(39, 81, 7, "Concórdia Banco S.A."),
            new Banco(40, 96, 5, "Banco BMeF de Serviços de Liquidação e Custódia S.A"),
            new Banco(41, 104, 0, "Caixa Econômica Federal"),
            new Banco(42, 107, 4, "Banco BBM S.A."),
            new Banco(43, 116, 3, "Banco Único S.A."),
            new Banco(44, 151, 1, "Banco Nossa Caixa S.A."),
            new Banco(45, 175, 9, "Banco Finasa S.A."),
            new Banco(46, 184, 8, "Banco Itaú BBA S.A."),
            new Banco(47, 204, 6, "Banco Bradesco Cartões S.A."),
            new Banco(48, 208, 9, "Banco UBS Pactual S.A."),
            new Banco(49, 212, 7, "Banco Matone S.A."),
            new Banco(50, 213, 5, "Banco Arbi S.A."),
            new Banco(51, 214, 3, "Banco Dibens S.A."),
            new Banco(52, 215, 1, "Banco Comercial e de Investimento Sudameris S.A."),
            new Banco(53,217, 8, "Banco John Deere S.A."),
            new Banco(54, 218, 6, "Banco Bonsucesso S.A."),
            new Banco(55, 222, 4, "Banco Calyon Brasil S.A."),
            new Banco(56, 224, 0, "Banco Fibra S.A."),
            new Banco(57, 225, 9, "Banco Brascan S.A."),
            new Banco(58, 229, 1, "Banco Cruzeiro do Sul S.A."),
            new Banco(59, 230, 5, "Unicard Banco Múltiplo S.A."),
            new Banco(60, 233, 0, "Banco GE Capital S.A."),
            new Banco(61, 237, 2, "Banco Bradesco S.A."),
            new Banco(62, 241, 0, "Banco Clássico S.A."),
            new Banco(63, 243, 7, "Banco Máxima S.A."),
            new Banco(64, 246, 1, "Banco ABC Brasil S.A."),
            new Banco(65, 248, 8, "Banco Boavista Interatlântico S.A."),
            new Banco(66, 249, 6, "Banco Investcred Unibanco S.A."),
            new Banco(67, 250, 0, "Banco Schahin S.A."),
            new Banco(68, 252, 6, "Banco Fininvest S.A."),
            new Banco(69, 254, 2, "Paraná Banco S.A."),
            new Banco(70, 263, 1, "Banco Cacique S.A."),
            new Banco(71, 265, 8, "Banco Fator S.A."),
            new Banco(72, 266, 6, "Banco Cédula S.A."),
            new Banco(73, 300, 0, "Banco de La Nacion Argentina"),
            new Banco(74, 318, 2, "Banco BMG S.A."),
            new Banco(75, 320, 4, "Banco Industrial e Comercial S.A."),
            new Banco(76, 341, 7, "Banco Itaú S.A."),
            new Banco(77, 356, 5, "Banco Real S.A."),
            new Banco(78, 366, 2, "Banco Société Générale Brasil S.A."),
            new Banco(79, 370, 0, "Banco WestLB do Brasil S.A."),
            new Banco(80, 376, 0, "Banco J. P. Morgan S.A."),
            new Banco(81, 389, 1, "Banco Mercantil do Brasil S.A."),
            new Banco(82, 394, 8, "Banco Finasa BMC S.A."),
            new Banco(83, 399, 9, "HSBC Bank Brasil S.A. - Banco Múltiplo"),
            new Banco(84, 409, 0, "UNIBANCO - União de Bancos Brasileiros S.A."),
            new Banco(85, 412, 0, "Banco Capital S.A."),
            new Banco(86, 422, 7, "Banco Safra S.A."),
            new Banco(87, 453, 7, "Banco Rural S.A."),
            new Banco(88, 456, 1, "Banco de Tokyo-Mitsubishi UFJ Brasil S.A."),
            new Banco(89, 464, 2, "Banco Sumitomo Mitsui Brasileiro S.A."),
            new Banco(90, 473, 1, "Banco Caixa Geral - Brasil S.A."),
            new Banco(91, 477, 4, "Citibank N.A."),
            new Banco(92, 479, 0, "Banco ItaúBank S.A"),
            new Banco(93, 487, 1, "Deutsche Bank S.A. - Banco Alemão"),
            new Banco(94, 488, 0, "JPMorgan Chase Bank"),
            new Banco(95, 492, 8, "ING Bank N.V."),
            new Banco(96, 494, 4, "Banco de La Republica Oriental del Uruguay"),
            new Banco(97, 495, 2, "Banco de La Provincia de Buenos Aires"),
            new Banco(98, 505, 3, "Banco Credit Suisse (Brasil) S.A."),
            new Banco(99, 600, 9, "Banco Luso Brasileiro S.A."),
            new Banco(100, 604, 1, "Banco Industrial do Brasil S.A."),
            new Banco(101, 610, 6, "Banco VR S.A."),
            new Banco(102, 611, 4, "Banco Paulista S.A."),
            new Banco(103, 612, 2, "Banco Guanabara S.A."),
            new Banco(104, 613, 0, "Banco Pecúnia S.A."),
            new Banco(105, 623, 8, "Banco Panamericano S.A."),
            new Banco(106, 626, 2, "Banco Ficsa S.A."),
            new Banco(107, 1630, 0, "Banco Intercap S.A."),
            new Banco(108, 633, 5, "Banco Rendimento S.A."),
            new Banco(109, 634, 3, "Banco Triângulo S.A."),
            new Banco(110, 637, 8, "Banco Sofisa S.A."),
            new Banco(111, 638, 6, "Banco Prosper S.A."),
            new Banco(112, 641, 6, "Banco Alvorada S.A."),
            new Banco(113, 643, 2, "Banco Pine S.A."),
            new Banco(114, 652, 1, "Itaú Unibanco Holding S.A."),
            new Banco(115, 653, 0, "Banco Indusval S.A."),
            new Banco(116, 654, 8, "Banco A.J.Renner S.A."),
            new Banco(117, 655, 6, "Banco Votorantim S.A."),
            new Banco(118, 707, 2, "Banco Daycoval S.A."),
            new Banco(119, 719, 6, "Banif-Banco Internacional do Funchal (Brasil)S.A."),
            new Banco(120, 721, 8, "Banco Credibel S.A."),
            new Banco(121, 724, 2, "Banco Porto Seguro S.A."),
            new Banco(122, 734, 0, "Banco Gerdau S.A."),
            new Banco(123, 735, 8, "Banco Pottencial S.A."),
            new Banco(124, 738, 2, "Banco Morada S.A."),
            new Banco(125, 739, 0, "Banco BGN S.A."),
            new Banco(126, 740, 4, "Banco Barclays S.A."),
            new Banco(127, 741, 2, "Banco Ribeirão Preto S.A."),
            new Banco(128, 743, 9, "Banco Semear S.A."),
            new Banco(129, 744, 7, "BankBoston N.A."),
            new Banco(130, 745, 5, "Banco Citibank S.A."),
            new Banco(131, 746, 3, "Banco Modal S.A."),
            new Banco(132, 747, 1, "Banco Rabobank International Brasil S.A."),
            new Banco(133, 748, 0, "Banco Cooperativo Sicredi S.A."),
            new Banco(134, 749, 8, "Banco Simples S.A."),
            new Banco(135, 751, 0, "Dresdner Bank Brasil S.A. - Banco Múltiplo"),
            new Banco(136, 752, 8, "Banco BNP Paribas Brasil S.A."),
            new Banco(137, 753, 6, "NBC Bank Brasil S.A. - Banco Múltiplo"),
            new Banco(138, 755, 2, "Banco Merrill Lynch de Investimentos S.A."),
            new Banco(139, 756, 0, "Banco Cooperativo do Brasil S.A. - BANCOOB"),
            new Banco(140, 757, 9, "Banco KEB do Brasil S.A.")
        };
    }
}